# -*- coding: utf-8 -*-
"""Arithmatic operation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16guKOA0WlrdRr23cXUqVZ57daNlfsF8a
"""

a=int(input("enter a number:"))
b=int(input("enter a number"))
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)