# -*- coding: utf-8 -*-
"""calculate Area and perimeter of a rectangle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135hMDxirk8WUTk3KlCeyR2LhV-3RxDBw
"""

L=float(input('enter length:'))
w=float(input("enter width"))
area=(L*w)
perimeter=2*(L+w)
print('area is:',area)
print('perimeter is:',perimeter)