# -*- coding: utf-8 -*-
"""Convertion of  min to hours

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGycm2RMaPsRhGBdFn3veOlMrpm4a3_G
"""

min=int(input("enter the value"))
hours = min//60
b=min%60
print(hours)
print(b)