# -*- coding: utf-8 -*-
"""day 01 python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MORZxx9N77BE_j6RBsNIBCQoN5HT5Maz
"""

# print("likhi")+"""
"""sgiddfbdkvfdg"""

X=10 # integer
y=3.14 # Float
name ="john"
print(name)

print (10)
b =3.14
name="likhi"
print(b,name)

a=10
b=3.14
name="rajesh"
print(a,b,name)
print(name +' very good')

name=input("enter student name:")
a=int(input("enter the value:"))
print(name + "a")

name=input("Enter your name:")
a = ("Hello + 10 :")