# -*- coding: utf-8 -*-
"""Simple Interest Calculatar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126fX0H6MYUXxwWOaH0PBd6OQLl71QN30
"""

p=float(input('enter the value'))
t=float(input('number of year'))
r=float(input('rate of interset'))
SI=(p*t*r)/100
print(SI)