# -*- coding: utf-8 -*-
"""Temperature

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-y-xyv3BH_19wOwFJk2zzxUsP1x1RQa

Temperature Converter
"""

celsius=float(input("enter temperature in Celcius:"))
fahrenheit=(celsius*9/5)+32
print("Temperature in Fahrenheit:",fahrenheit)